[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/sagudev/cross-aarch64-unknown-linux-gnu:docker-images"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/sagudev/cross-armv7-unknown-linux-gnueabihf:docker-images"
