[package]
links = "properties_glue"
name = "mozjs-properties_glue"
version = "153.0.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
icu_properties = "2.1.2"
icu_collections = { features = ["alloc"], package = "mozjs-icu_collections", path = "../icu_collections" }
icu_casemap = "2"

[build-dependencies.cbindgen]
version = "0.29.4"
